### PR TITLE
MINOR FIX: Ignore Default Values Parameter for Post and Put

### LINKED ISSUE #63: MINOR FIX: Rename ignoreNulls to ignoreDefaultValues
The Json Serializer setting is for "DefaultValueHandling". This would better reflect the parameters intent.

### PR DESCRIPTION
**Pull request by BrianLParker**
This changes the parameter name the previous version that is new and has a default value.

Ignore nulls is what we spoke about in the discussions.
The Json Serializer setting is for "DefaultValueHandling"
This name better reflects the intent of the parameter.
I have updated both RESTFulSense and RESTFulSense.WebAssembly for aligment. I would recommend a version bump for both and maybe even alignment of the numbers.

Closes #63

### CODE REVIEW

File: RESTFulSense.WebAssembly/Clients/RESTFulApiClient.Conversions.cs [hunk 1]
```diff
@@ -56,5 +61,11 @@ private static StreamContent ConvertToStreamContent<T>(T content, string mediaTy
             return contentStream;
         }
 
+        private static JsonSerializerSettings CreateJsonSerializerSettings(bool ignoreDefaultValues)
+        {
+            DefaultValueHandling defaultValueHandling = ignoreDefaultValues ? DefaultValueHandling.Ignore : DefaultValueHandling.Include;
+            var jsonSerializerSettings = new JsonSerializerSettings { DefaultValueHandling = defaultValueHandling };
+            return jsonSerializerSettings;
```
Comment (cjdutoit) [inline RESTFulSense.WebAssembly/Clients/RESTFulApiClient.Conversions.cs:68]: Add a new line before `return jsonSerializerSettings;`

File: RESTFulSense.WebAssembly/Clients/RESTFulApiClient.cs [hunk 2]
```diff
@@ -72,17 +77,20 @@ public async ValueTask<T> GetContentAsync<T>(string relativeUrl, CancellationTok
...
         public async ValueTask<TResult> PostContentAsync<TContent, TResult>(
             string relativeUrl,
             TContent content,
-            string mediaType = "text/json")
+            string mediaType = "text/json",
+            bool ignoreDefaultValues = false)
         {
-            HttpContent contentString = ConvertToHttpContent(content, mediaType);
+            HttpContent contentString =
+                ConvertToHttpContent(content, mediaType, ignoreDefaultValues);
```
Comment (cjdutoit) [inline RESTFulSense.WebAssembly/Clients/RESTFulApiClient.cs:93]: Fix indentation

**Review by cjdutoit — APPROVED** [review]
